name: Published and Edited Diff Workflow

on: 
  release: 
    types: [published, edited]
    branches:
      - Master

jobs:
  diff_published:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history and tags

      - name: Set up GitHub CLI
        run: |
          curl -sL https://github.com/cli/cli/releases/download/v2.26.0/gh_2.26.0_linux_amd64.tar.gz | tar xz
          sudo mv gh_2.26.0_linux_amd64/bin/gh /usr/local/bin/

      - name: Authenticate GitHub CLI
        run: |
            gh auth login --with-token <<< "${{ secrets.TOKEN }}"

      - name: list release
        run: |
          gh release list

      - name: Get letest and privious release List
        run: |
          gh release list | awk 'NR==1 {latest=$0} NR==2 {previous=$0} END {print "Latest release: " latest "\nPrevious release: " previous}'
