name: Published and Edited Diff Workflow

on: 
  release: 
    types: [published, edited]
    branches:
      - master

jobs:
  diff_published:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history and tags

      - name: Set up GitHub CLI
        uses: cli/cli@v2

      - name: Fetch release information
        id: fetch_releases
        run: |
          gh release list --json tagName --jq '.[] | .tagName' > tags.txt

      - name: Read release tags
        id: read_tags
        run: |
          tags=$(cat tags.txt)
          echo "Tags: $tags"
          echo "::set-output name=tags::$tags"

      - name: Perform diff between releases
        run: |
          tags=(${ { steps.read_tags.outputs.tags } })
          if [ ${ #tags[@] } -ge 2 ]; then
            echo "Comparing ${tags[0]} and ${tags[1]}"
            git diff ${tags[0]} ${tags[1]} > diff.txt
            cat diff.txt
          else
            echo "Not enough tags to perform a diff."
          fi
