name: Published and Edited Diff Workflow

on: 
  release: 
    types: [published, edited]
    branches:
      - Master

jobs:
  diff_published:
    runs-on: ubuntu-latest
    outputs:
      changedfiles: ${{ steps.set-changed-files.outputs.changedfiles }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history and tags

      - name: Set up GitHub CLI
        run: |
          curl -sL https://github.com/cli/cli/releases/download/v2.26.0/gh_2.26.0_linux_amd64.tar.gz | tar xz
          sudo mv gh_2.26.0_linux_amd64/bin/gh /usr/local/bin/

      - name: Authenticate GitHub CLI
        run: |
            gh auth login --with-token <<< "${{ secrets.TOKEN }}"

      - name: list release
        run: |
          gh release list

      - name: Get latest and previous release tags
        id: get_tags
        run: |
          latest_tag=$(gh release list | awk 'NR==1' | awk '{print $(NF-1)}')
          previous_tag=$(gh release list | awk 'NR==2' | awk '{print $(NF-1)}')
          echo "Latest release tag is: $latest_tag"
          echo "Previous release tag is: $previous_tag"
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
          echo "PREVIOUS_TAG=$previous_tag" >> $GITHUB_ENV

      
      - name: Get list of changed files
        id: set-changed-files
        run: |
          changedfiles=$(git diff --name-only --diff-filter=ACMRT ${{ env.previous_tag }} ${{ env.LATEST_TAG }} | uniq | jq -R -s -c 'split("\n")[:-1]')
          echo "changedfiles=$changedfiles" >> $GITHUB_OUTPUT

      - name: Output changed files
        run: |
            echo "Changed files between ${{ env.previous_tag }} and ${{ env.new_tag }}: ${{ steps.set-changed-files.outputs.changedfiles }}"