name: Published and Edited Diff Workflow

on: 
  release: 
    types: [published, edited]
    branches:
      - Master

jobs:
  diff_published:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history and tags

      - name: Set up GitHub CLI
        run: |
          curl -sL https://github.com/cli/cli/releases/download/v2.26.0/gh_2.26.0_linux_amd64.tar.gz | tar xz
          sudo mv gh_2.26.0_linux_amd64/bin/gh /usr/local/bin/

      - name: Authenticate GitHub CLI
        run: |
            gh auth login --with-token <<< "${{ secrets.TOKEN }}"
            gh release list

      - name: Fetch release information
        id: fetch_releases
        run: |
          gh release list > tags.txt

      - name: Read release tags
        id: read_tags
        run: |
          latest_tag=$(awk '{print $1}' tags.txt | head -n 1)
          previous_tag=$(awk '{print $1}' tags.txt | head -n 2 | tail -n 1)
          
          echo "_______________________________"
          echo "Latest Tag: $latest_tag"
          echo "Previous Tag: $previous_tag"
          echo "_______________________________"
          
          # Set environment variables
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
          echo "PREVIOUS_TAG=$previous_tag" >> $GITHUB_ENV


    #   - name: Perform diff between releases
    #     run: |
    #       tags=(${ { steps.read_tags.outputs.tags } })
    #       if [ ${ #tags[@] } -ge 2 ]; then
    #         echo "Comparing ${tags[0]} and ${tags[1]}"
    #         git diff ${tags[0]} ${tags[1]} > diff.txt
    #         cat diff.txt
    #       else
    #         echo "Not enough tags to perform a diff."
    #       fi
