name: Tag Diff Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  diff_between_tags:
    runs-on: ubuntu-latest
    outputs:
      changedfiles: ${{ steps.set-changed-files.outputs.changedfiles }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all tags and history

      - name: Delete local tag if it exists
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          if git show-ref --tags | grep -q "refs/tags/$TAG_NAME$"; then
            git tag -d $TAG_NAME
          fi

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get the last two tags
        id: get_tags
        run: |
          LAST_TWO_TAGS=$(git tag --sort=-creatordate | head -n 2)
          NEW_TAG=$(echo "$LAST_TWO_TAGS" | head -n 1)
          PREVIOUS_TAG=$(echo "$LAST_TWO_TAGS" | tail -n 1)
          echo "new_tag=$NEW_TAG" >> $GITHUB_ENV
          echo "previous_tag=$PREVIOUS_TAG" >> $GITHUB_ENV
          echo "New Tag is : $NEW_TAG"
          echo  "Previous Tag is : $PREVIOUS_TAG"

      - name: Get list of changed files
        id: set-changed-files
        run: |
          changedfiles=$(git diff --name-only --diff-filter=ACMRT ${{ env.previous_tag }} ${{ env.new_tag }} | uniq | jq -R -s -c 'split("\n")[:-1]')
          echo "changedfiles=$changedfiles" >> $GITHUB_OUTPUT


      - name: Output changed files
        run: |
          echo ""
          echo ""
          echo "Changed files between ${{ env.previous_tag }} and ${{ env.new_tag }}: "
          echo "${{ steps.set-changed-files.outputs.changedfiles }}"